// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorTheme } from "./ColorTheme.d";

export type Config = { colorTheme: ColorTheme, };
