// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorTheme } from "./ColorTheme.d";
import type { Keybinds } from "./Keybinds.d";

export type Config = { colorTheme: ColorTheme, keybinds: Keybinds, };
