// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookmarkRecord = { id: bigint, title: string, url: string, description: string, tag_count: number, };

export type InsertBookmarkRequest = { title: string, url: string, description: string, tags: Array<string>, };

export type TagRecord = { id: bigint, name: string, };
