// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalKeybind } from "../GlobalKeybind";
import type { Keys } from "../Keys";

export type Keybinds = { global: GlobalKeybind, focusDownBookmarkList: Keys, focusUpBookmarkList: Keys, closeWindow: Keys, focusDownSuggestionWindow: Keys, focusUpSuggestionWindow: Keys, addFocusedSuggestionItem: Keys, popInputedTag: Keys, closeSuggestionWindow: Keys, navigateCreateNewBookmark: Keys, openUrl: Keys, cancelCreateNewBookmark: Keys, doneCreateNewBookmark: Keys, takeInputTag: Keys, };
