// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookmarkItemColorTheme = { tag: string, title: string, desc: string, bg: string, focusBg: string, };
