// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Keys } from "./Keys";

export type GlobalKeybind = { toggleWindowVisible: Keys, };
