// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagItem = { bg: string, borderColor: string, exists: string, notExists: string, };
