name: "CI"

on:
  push:
    branches:
      - development 

# 参考URL: https://blog.lacolaco.net/posts/github-actions-yarn-cache/
env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install packages
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 librsvg2-dev -y

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.platform }}-${{ matrix.args }}
          workspaces: 'src-tauri -> target'

      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1

      - name: install frontend dependencies
        run: yarn --frozen-lockfile && yarn install --network-timeout 600000 --prefer-offline
      
      - name: test
        run: yarn run test

      - name: lint
        run: yarn run lint

      - name: fmt
        run: yarn run fmt
      
      - name: test rust
        working-directory: src-tauri
        run: cargo test

      - name: rust lint
        working-directory: src-tauri
        run: cargo clippy
      
      - name: rust fmt
        working-directory: src-tauri
        run: cargo fmt --all -- --check

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}